# Synthesize some views of a textured octomap

geometry_msgs/Point[] positions
geometry_msgs/Vector3[] orientations
uint32 h
uint32 w
float32 fx
float32 fy
float32 cx
float32 cy
---
sensor_msgs/Image[] images 
sensor_msgs/Image[] depths 
